name: t_3dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda>=12.1
  - plyfile
  - python=3.12.9
  - pip=25.0
  - pytorch>=2.2
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - opencv-python
    - natsort
    - scipy
    - imageio==2.31.2
    - imageio-ffmpeg==0.4.9
    - opencv-python
    - ftfy
    - lpips
    - plyfile
    - git+https://github.com/mhamilton723/FeatUp.git
